version: 2
models:
  - name: officine
    description: 'Le local physique ou point de vente caractérise l''officine\n\nL''officine existe au regard des autorités médicales par son numéro unique CIP\n\nUne officine est stable dans le temps sur son local physique\n\nL''officine peut changer de titulaire/exploitant dans le temps\n\nL''officine est est l''unique point d''entrée pour réaliser des opération'
    columns:
      - name: date_fermeture
        description: 'La date de fermeture est enregistrée auprès des autorités médicales\nLe numéro de CIP unique devient invalide pour effectuer toute opération'
        data_type: 'DATE'
      - name: cip
        description: '1) Qu''est-ce que le code CIP officinal ?\nLe code CIP officinal (ou code établissement CIP) n’est pas le même que le code CIP des médicaments.\nIci, on parle bien du code d’identification de l’officine en tant que structure, utilisé notamment pour :\n*les échanges avec l’assurance maladie (télétransmission SESAM-Vitale),\n*les logiciels de gestion officinale (LGO),\n*la facturation des prestations de santé,\n*la traçabilité des flux de facturation.\n\nIl s''agit d''un identifiant informatique indispensable au fonctionnement quotidien de l’officine.\n\n2) Qui attribue le code CIP officinal ?\nLe **code CIP officinal est attribué par le CFDP (ex-CERP/CIP) devenu aujourd’hui GIE SESAM-Vitale / Cegedim Santé via l’organisme CIP Santé.\n\nEn pratique :\n\nDès que l’officine a son SIRET et est déclarée auprès de l''assurance maladie (CPAM) et de l''Ordre des pharmaciens, le pharmacien (ou son prestataire informatique) fait une demande d’attribution de code CIP officinal.\n\nCIP Santé génère ce code qui permet ensuite de paramétrer :\n*le logiciel de gestion de l’officine (LGO),\n*la télétransmission des feuilles de soins électroniques,\n*la sécurisation des échanges avec l’assurance maladie.\n\n3) Sur quelle base est attribué ce code ?\nNuméro SIRET de l’officine.\n\nConventionnement auprès de la CPAM (obligatoire pour la télétransmission).\n\nInformations administratives validées (Ordre, ARS…).\n\nC’est donc bien après l’obtention du SIRET que le code CIP officinal est généré.'
        data_type: 'STRING'
        constraints:
          - type: primary_key
          - type: not_null
      - name: date_ouverture
        description: 'La date d''obtention du code CIP auprès des autorités médicales'
        data_type: 'DATE'
  - name: societe_juridique
    description: 'L''entité juridique en lien avec ses établissements\n\nLa clé métier est le SIREN'
    columns:
      - name: tvaintra_communautaire
        description: ''
        data_type: 'STRING'
      - name: raison_sociale
        description: ''
        data_type: 'STRING'
      - name: siren
        description: ''
        data_type: 'STRING'
        constraints:
          - type: primary_key
          - type: not_null
  - name: type_etablissement
    description: 'Le type d''établissement exemple : officine (code OFF)'
    columns:
      - name: libelle
        description: ''
        data_type: 'STRING'
      - name: code
        description: ''
        data_type: 'STRING'
        constraints:
          - type: primary_key
          - type: not_null
  - name: etablissement
    description: 'L''établissement physique en lien avec la société juridique, exemple une officine\n\nLa clé métier est le code EBX dans le SI Biogaran\n\nLe SIRET est la clé métier publique, cette clé permet la réconciliation de flux de transactions en provenance de partenaires hors du SI Biogaran\n\nL''établissement a une durée de vie, date d''ouverture et de fermeture\n\nLE NRID vient de NEO et s''applique à toutes les tables (dans la couche DATAHUB)'
    columns:
      - name: titulaire_officine
        description: 'Le titulaire/exploitant de l''officine est légalement un SIRET\nL''établissement est titulaire/exploitant d''une officine uniquement s''il est du type Officine'
        data_type: 'STRING'
        constraints:
          - type: foreign_key
        tests:
          - relationships:
            field: cip
            to: ref('Officine')
      - name: date_fermeture
        description: 'La date de fermeture de l''établissement'
        data_type: 'DATE'
      - name: siret
        description: 'Le SIRET est la clé métier publique, cette clé permet la réconciliation de flux de transactions en provenance de partenaires hors du SI Biogaran'
        data_type: 'STRING'
      - name: code_ebx
        description: 'Correspond au code_officine\n\nLe code offcine est relié au SIREN et stable dans le temps\n\nIl est indéendant du déménagement physique de l''officine (adresse postale)'
        data_type: 'STRING'
        constraints:
          - type: primary_key
          - type: not_null
      - name: type_etablissement
        description: ''
        data_type: 'STRING'
        constraints:
          - type: foreign_key
        tests:
          - relationships:
            field: code
            to: ref('TypeEtablissement')
      - name: etablissement_societe_juridique
        description: ''
        data_type: 'STRING'
        constraints:
          - type: foreign_key
        tests:
          - relationships:
            field: siren
            to: ref('SocieteJuridique')
      - name: date_ouverture
        description: 'La date d''ouverture de l''établissement'
        data_type: 'DATE'
